"""
Extract structured JSONL from step8-generated HTML files.

When only HTML exists (no companion JSONL), this script parses the HTML DOM
to reconstruct the JSONL data that step8 would have produced.

Usage:
  python3 html_to_jsonl.py <input.html> <output.jsonl>
"""
import re, json, sys, os, io
from html import unescape as html_unescape
from html.parser import HTMLParser

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

if len(sys.argv) < 3:
    print("Usage: python3 html_to_jsonl.py <input.html> <output.jsonl>")
    sys.exit(1)

html_path = sys.argv[1]
out_path = sys.argv[2]

with open(html_path, "r", encoding="utf-8") as f:
    html = f.read()


# ── Strategy: use regex to extract structured data from the known HTML layout ──
# The HTML is generated by step8_generate_html.py with known CSS classes.

def extract_text(html_fragment):
    """Strip HTML tags from a fragment and unescape HTML entities."""
    return html_unescape(re.sub(r"<[^>]+>", "", html_fragment).strip())


def parse_price(price_str):
    """Extract numeric price from a string like '$29.99' or '29.99'."""
    m = re.search(r"[\d,]+\.?\d*", price_str.replace(",", ""))
    return m.group(0) if m else ""


# ── Split into user blocks ──
# User blocks may be <details class="ub"> or <div class="ub">
if '<details class="ub">' in html:
    user_blocks = re.split(r'<details\s+class="ub">', html)[1:]
else:
    user_blocks = re.split(r'<div\s+class="ub">', html)[1:]
print(f"Found {len(user_blocks)} user blocks")

users = []

for ui, ub in enumerate(user_blocks):
    user = {
        "stableid": "",
        "userShoppingProfile": {},
        "recentShoppingEvents": "",
        "journeys": [],
    }

    # ── Extract user ID (stable ID if present, else User N) ──
    uid_match = re.search(r'class="uid[^"]*">([^<]+)', ub)
    if uid_match:
        raw_uid = uid_match.group(1).strip().rstrip("…").rstrip(".")
        user["stableid"] = raw_uid
    else:
        user["stableid"] = f"user_{ui+1:04d}"

    # ── Extract events ──
    events = []
    for ev_match in re.finditer(r'class="ev"[^>]*>(.*?)</div>', ub, re.DOTALL):
        events.append(extract_text(ev_match.group(1)))
    user["recentShoppingEvents"] = "\n".join(events)

    # ── Extract shopping profile ──
    # Profile is in a <div class="pc"> section
    profile = {}
    pc_match = re.search(r'class="pc">(.*?)</div>\s*</details>', ub, re.DOTALL)
    if pc_match:
        pc_html = pc_match.group(1)
        for row in re.finditer(r'class="pk">([^<]+)</.*?class="pv">([^<]+)', pc_html, re.DOTALL):
            key = row.group(1).strip()
            val = row.group(2).strip()
            # Try to parse as JSON list
            if val.startswith("[") or val.startswith("{"):
                try:
                    val = json.loads(val)
                except json.JSONDecodeError:
                    pass
            profile[key] = val
    user["userShoppingProfile"] = {"userShoppingProfile": profile}

    # ── Extract journeys ──
    journey_blocks = re.split(r'<details\s+class="journey-card">', ub)[1:]

    for jb in journey_blocks:
        journey = {}

        # Journey type
        jtype_match = re.search(r'class="jt tag-(\w+)"', jb)
        journey["journeyType"] = jtype_match.group(1) if jtype_match else ""

        # Title
        title_match = re.search(r'class="jtitle">([^<]+)', jb)
        journey["title"] = html_unescape(title_match.group(1).strip()) if title_match else ""

        # Description
        desc_match = re.search(r'class="jd">([^<]+)', jb)
        journey["description"] = html_unescape(desc_match.group(1).strip()) if desc_match else ""

        # Reason (WhyAmISeeingThis)
        reason_match = re.search(r'class="jr">([^<]+)', jb)
        journey["reason"] = html_unescape(reason_match.group(1).strip()) if reason_match else ""

        # Conversation starter
        cs_match = re.search(r'class="jct">([^<]+)', jb)
        journey["conversationStarter"] = html_unescape(cs_match.group(1).strip()) if cs_match else ""

        # Stats (RankingSummary)
        stats = {}
        rs_match = re.search(r'class="rsumm">(.*?)</div>', jb, re.DOTALL)
        if rs_match:
            rs_text = extract_text(rs_match.group(1))
            for kv in re.finditer(r'(\w[\w\s]*?):\s*([\d.]+)', rs_text):
                stats[kv.group(1).strip()] = int(kv.group(2)) if kv.group(2).isdigit() else kv.group(2)
        # Also try _L3Rerank stats
        l3_match = re.search(r'class="rs">(.*?)</div>', jb, re.DOTALL)
        if l3_match:
            l3_text = extract_text(l3_match.group(1))
            for kv in re.finditer(r'(\w[\w_]*?):\s*([\d.]+)', l3_text):
                stats[kv.group(1).strip()] = int(kv.group(2)) if kv.group(2).isdigit() else kv.group(2)
        journey["stats"] = stats

        # Products
        products = []
        product_cards = re.split(r'<div\s+class="product-card">', jb)[1:]

        for pc in product_cards:
            prod = {}

            # Title
            pt_match = re.search(r'class="product-title"[^>]*>(?:<a[^>]*>)?([^<]+)', pc)
            prod["Title"] = html_unescape(pt_match.group(1).strip()) if pt_match else ""

            # Seller
            ps_match = re.search(r'class="product-seller"[^>]*>([^<]+)', pc)
            prod["Seller"] = html_unescape(ps_match.group(1).strip()) if ps_match else ""

            # Price
            pp_match = re.search(r'class="product-price"[^>]*>([^<]+)', pc)
            if pp_match:
                prod["OriginalPrice"] = parse_price(pp_match.group(1))

            # Brand
            pb_match = re.search(r'class="product-brand"[^>]*>([^<]+)', pc)
            prod["Brand"] = html_unescape(pb_match.group(1).strip()) if pb_match else ""

            # Query source
            pq_match = re.search(r'class="product-query"[^>]*>([^<]+)', pc)
            prod["OriginalQuery"] = html_unescape(pq_match.group(1).strip().lstrip("🔍 ").strip()) if pq_match else ""

            # Rank
            rank_match = re.search(r'class="product-rank"[^>]*>([^<]+)', pc)
            if rank_match:
                rank_text = rank_match.group(1).strip()
                rank_num = re.search(r'#?(\d+)', rank_text)
                prod["DisplayPosition"] = int(rank_num.group(1)) if rank_num else ""

            # Original SLM Rank
            orig_match = re.search(r'class="orig-rank"[^>]*>[^#]*#?(\d+)', pc)
            if orig_match:
                prod["OriginalSLMRank"] = int(orig_match.group(1))

            # OfferUrl
            url_match = re.search(r'class="product-title"[^>]*><a[^>]*href="([^"]+)"', pc)
            prod["OfferUrl"] = url_match.group(1) if url_match else ""

            # ImageUrl
            img_match = re.search(r'<img[^>]*src="([^"]+)"', pc)
            prod["ImageUrl"] = img_match.group(1) if img_match else ""

            # Attributes (Gender, AgeGroup)
            attrs_match = re.search(r'class="product-attrs"[^>]*>(.*?)</div>', pc, re.DOTALL)
            if attrs_match:
                attrs_text = extract_text(attrs_match.group(1))
                prod["Gender"] = ""
                prod["AgeGroup"] = ""
                for part in attrs_text.split("|"):
                    part = part.strip()
                    if part.lower() in ("male", "female", "unisex"):
                        prod["Gender"] = part
                    elif part.lower() in ("adult", "kids", "infant", "toddler"):
                        prod["AgeGroup"] = part

            # global_offer_id - try to extract from URL or data attribute
            gid_match = re.search(r'data-gid="([^"]+)"', pc)
            if gid_match:
                prod["global_offer_id"] = gid_match.group(1)
            else:
                # Generate a deterministic ID from title+seller
                prod["global_offer_id"] = f"html_{hash((prod['Title'], prod['Seller'])) & 0xFFFFFFFF:08x}"

            products.append(prod)

        journey["products"] = products
        user["journeys"].append(journey)

    users.append(user)
    print(f"  User {ui+1}: {user['stableid'][:20]}... | {len(user['journeys'])} journeys | {sum(len(j['products']) for j in user['journeys'])} products")

# ── Write JSONL ──
with open(out_path, "w", encoding="utf-8") as f:
    for u in users:
        f.write(json.dumps(u, ensure_ascii=False) + "\n")

print(f"\nWrote {len(users)} users → {out_path}")
