"""Step 2e: Build Profile-to-Journey SFT Data

Creates SFT training data for predicting shopping journeys from a user's
shopping profile combined with their most recent shopping events.

Unlike s2_build_event2journey_sft_data.py which uses only the full event
history, this task leverages the structured shopping profile (generated by
pre_s3_construct_shopping_profile.py) as the primary user representation,
supplemented by a small number of recent events for recency context.

Data sources:
  shopping_journeys.json (from pre_s3_construct_shopping_journey.py)
    Format: { UserId: {user_shopping_events, journeys: [{title, reason, product_ids}]} }
  shopping_profiles.tsv (from pre_s3_construct_shopping_profile.py)
    Format: TSV with columns UserId, ShoppingProfile (JSON string)
  id2meta.json (from s1_generate_tid.py)
    Format: { ItemId: {title, description, categories, summary_words, ...} }

Pipeline:
  1. Load shopping_journeys.json, shopping_profiles.tsv, and id2meta.json.
  2. Join on UserId: only keep users present in both journeys and profiles.
  3. For each user, resolve product_ids to TIDs via id2meta.
  4. Build instruction/input/output for SFT training.
     Input = shopping profile JSON + most recent N events.
     Output = structured JSON with ContinuedJourneys.
  5. Save full and simplified versions.

Usage:
    python s2_build_profile2journey_sft_data.py \\
        --shopping_journey_file ./raw_data/shopping_journeys.json \\
        --shopping_profile_file ./raw_data/shopping_profiles.tsv \\
        --id2meta_file ./processed/id2meta.json \\
        --output_dir ./sft_data \\
        --max_recent_events 10 \\
        --max_products_per_journey 10
"""

import os
import csv
import json
import sys
import argparse
from collections import defaultdict
from tqdm import tqdm
import numpy as np

# Increase CSV field size limit to handle very large fields
csv.field_size_limit(sys.maxsize)


# =============================================================================
# Constants
# =============================================================================

# Default number of most recent events to include in the input.
DEFAULT_MAX_RECENT_EVENTS = 10

# Maximum number of product TIDs to include per journey in the output.
DEFAULT_MAX_PRODUCTS = 10


# =============================================================================
# Data Loading
# =============================================================================

def load_shopping_profiles(profile_file):
    """Load shopping profiles from TSV file.

    Args:
        profile_file: Path to shopping_profiles.tsv with columns
            UserId and ShoppingProfile (JSON string).

    Returns:
        Dict mapping UserId -> profile JSON string.
    """
    profiles = {}
    with open(profile_file, "r", encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader, None)
        if header is None:
            return profiles

        col_map = {name.strip(): idx for idx, name in enumerate(header)}
        uid_idx = col_map.get("UserId", 0)
        profile_idx = col_map.get("ShoppingProfile", 1)

        for row in reader:
            if len(row) <= max(uid_idx, profile_idx):
                continue
            user_id = row[uid_idx].strip()
            profile_text = row[profile_idx].strip()
            if user_id and profile_text:
                profiles[user_id] = profile_text

    return profiles


# =============================================================================
# Utility Functions
# =============================================================================

def get_item_tid(item_id, id2meta):
    """Get the text ID (7 summary words) for an item.

    Args:
        item_id: Item identifier string (GlobalOfferId).
        id2meta: Dict mapping item IDs to metadata with summary_words.

    Returns:
        List of 7 summary words, or None if not found or invalid.
    """
    if item_id not in id2meta:
        return None
    meta = id2meta[item_id]
    summary_words = meta.get("summary_words", [])
    if not summary_words or "" in summary_words:
        return None
    valid_words = [
        word.replace("[", "").replace("]", "")
        for word in summary_words
        if word and word.strip()
    ]
    if len(valid_words) < 7:
        return None
    return valid_words[:7]


def resolve_journey_tids(journey, id2meta, max_products):
    """Resolve a journey's product_ids to text IDs.

    Args:
        journey: Dict with keys title, reason, product_ids.
        id2meta: Item ID to metadata mapping.
        max_products: Maximum number of products to include.

    Returns:
        Dict with title, reason, product_tids (list of 7-word lists),
        or None if no products could be resolved.
    """
    product_tids = []
    for pid in journey.get("product_ids", []):
        tid = get_item_tid(pid, id2meta)
        if tid is not None:
            product_tids.append(tid)
            if len(product_tids) >= max_products:
                break

    if not product_tids:
        return None

    return {
        "title": journey.get("title", ""),
        "reason": journey.get("reason", ""),
        "product_tids": product_tids,
    }


def build_output_json(resolved_journeys):
    """Build the structured JSON output string for SFT training.

    Output format:
    {"ContinuedJourneys":[{"Title":"...","Reason":"...","ProductTIDs":[["a","b",...],...]},...]}"

    Args:
        resolved_journeys: List of dicts with title, reason, product_tids.

    Returns:
        JSON string.
    """
    continued = []
    for j in resolved_journeys:
        continued.append({
            "Title": j["title"],
            "Reason": j["reason"],
            "ProductTIDs": j["product_tids"],
        })
    return json.dumps({"ContinuedJourneys": continued}, ensure_ascii=False)


# =============================================================================
# SFT Sample Construction
# =============================================================================

def create_instruction(num_journeys):
    """Create the instruction text for the profile-to-journey prediction task.

    Args:
        num_journeys: Number of journeys to predict.

    Returns:
        Instruction string.
    """
    return (
        f"Based on the user's shopping profile and recent shopping events, "
        f"predict {num_journeys} shopping journey(s) the user is likely to pursue. "
        "Each journey includes a title, a reason, and recommended products as "
        'text IDs (7 slots each). Output JSON: '
        '{"ContinuedJourneys":[{"Title":"...","Reason":"...",'
        '"ProductTIDs":[["s1","s2","s3","s4","s5","s6","s7"],...]},...]}.'
    )


def create_sft_sample(
    user_id,
    profile_text,
    recent_events,
    resolved_journeys,
):
    """Create a single SFT training sample.

    Args:
        user_id: User identifier string.
        profile_text: Shopping profile JSON string.
        recent_events: List of recent event strings (most recent first).
        resolved_journeys: List of resolved journey dicts.

    Returns:
        SFT sample dict.
    """
    instruction = create_instruction(len(resolved_journeys))

    # Build input: profile + recent events
    input_lines = []

    input_lines.append("User Shopping Profile:")
    input_lines.append(profile_text)
    input_lines.append("")

    input_lines.append("Recent Shopping Events:")
    for idx, event in enumerate(recent_events, 1):
        if len(event) > 150:
            event = event[:150] + "..."
        input_lines.append(f"{idx} | {event}")

    input_lines.append("")
    input_lines.append("Predict the user's shopping journeys:")

    input_text = "\n".join(input_lines)

    # Build output: structured JSON
    output_text = build_output_json(resolved_journeys)

    return {
        "instruction": instruction,
        "input": input_text,
        "output": output_text,
        "metadata": {
            "user_id": user_id,
            "num_recent_events": len(recent_events),
            "num_journeys": len(resolved_journeys),
            "num_products_per_journey": [
                len(j["product_tids"]) for j in resolved_journeys
            ],
        },
    }


# =============================================================================
# Main Pipeline
# =============================================================================

def create_profile2journey_sft_data(
    shopping_journey_data,
    profiles,
    id2meta,
    max_recent_events=DEFAULT_MAX_RECENT_EVENTS,
    max_products=DEFAULT_MAX_PRODUCTS,
):
    """Create SFT data from shopping profiles + events -> journeys.

    Args:
        shopping_journey_data: Dict of UserId -> journey entry.
        profiles: Dict of UserId -> profile JSON string.
        id2meta: Item ID to metadata mapping.
        max_recent_events: Number of most recent events to include.
        max_products: Maximum products per journey.

    Returns:
        List of SFT sample dicts.
    """
    sft_data = []
    skip_reasons = defaultdict(int)
    total_entries = len(shopping_journey_data)

    # Statistics
    event_counts = []
    journey_counts = []
    product_counts = []

    for user_id, entry in tqdm(
        shopping_journey_data.items(),
        desc="Building profile2journey SFT data",
    ):
        # Must have a profile to join
        if user_id not in profiles:
            skip_reasons["no_profile"] += 1
            continue

        profile_text = profiles[user_id]

        user_events = entry.get("user_shopping_events", [])
        journeys = entry.get("journeys", [])

        if not user_events:
            skip_reasons["no_user_events"] += 1
            continue

        if not journeys:
            skip_reasons["no_journeys"] += 1
            continue

        # Take the most recent N events (events are ordered most-recent-first)
        recent_events = user_events[:max_recent_events]

        # Resolve all journeys' product IDs to TIDs
        resolved_journeys = []
        for journey in journeys:
            resolved = resolve_journey_tids(journey, id2meta, max_products)
            if resolved is not None:
                resolved_journeys.append(resolved)

        if not resolved_journeys:
            skip_reasons["no_resolvable_products"] += 1
            continue

        # Create the SFT sample
        sample = create_sft_sample(
            user_id=user_id,
            profile_text=profile_text,
            recent_events=recent_events,
            resolved_journeys=resolved_journeys,
        )
        sft_data.append(sample)

        # Track statistics
        event_counts.append(len(recent_events))
        journey_counts.append(len(resolved_journeys))
        for j in resolved_journeys:
            product_counts.append(len(j["product_tids"]))

    # Print statistics
    print(f"\nData statistics:")
    print(f"  Total journey entries:        {total_entries:>10,}")
    print(f"  Total profiles available:     {len(profiles):>10,}")
    print(f"  Generated samples:            {len(sft_data):>10,}")
    print(f"  Skipped entries:")
    for reason, count in sorted(skip_reasons.items(), key=lambda x: -x[1]):
        print(f"    - {reason:30s} {count:>10,}")

    if event_counts:
        arr = np.array(event_counts)
        print(f"\n  Recent events per sample:")
        print(f"    Min: {arr.min()}, Max: {arr.max()}, "
              f"Mean: {arr.mean():.1f}, Median: {np.median(arr):.1f}")

    if journey_counts:
        arr = np.array(journey_counts)
        print(f"\n  Journeys per sample:")
        print(f"    Min: {arr.min()}, Max: {arr.max()}, "
              f"Mean: {arr.mean():.1f}, Median: {np.median(arr):.1f}")
        jc_dist = defaultdict(int)
        for c in journey_counts:
            jc_dist[c] += 1
        for cnt in sorted(jc_dist.keys()):
            print(f"    {cnt} journey(s): {jc_dist[cnt]:>6,} samples")

    if product_counts:
        arr = np.array(product_counts)
        print(f"\n  Products per journey:")
        print(f"    Min: {arr.min()}, Max: {arr.max()}, "
              f"Mean: {arr.mean():.1f}, Median: {np.median(arr):.1f}")

    return sft_data


def save_sft_data(sft_data, output_file):
    """Save SFT data (full and training versions).

    Full version (with metadata): <name>_full.json
    Training version (instruction/input/output only): <name>.json

    Args:
        sft_data: List of SFT sample dicts.
        output_file: Path to the training JSON file.
    """
    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    # Full version with all metadata
    full_file = output_file.replace(".json", "_full.json")
    with open(full_file, "w", encoding="utf-8") as f:
        json.dump(sft_data, f, ensure_ascii=False, indent=2)
    print(f"Full data saved: {full_file}")

    # Training version (instruction, input, output only)
    training_data = [
        {
            "instruction": s["instruction"],
            "input": s["input"],
            "output": s["output"],
        }
        for s in sft_data
    ]
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(training_data, f, ensure_ascii=False, indent=2)
    print(f"Training data saved: {output_file}")


# =============================================================================
# Argument Parsing
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Build profile-to-journey SFT data from shopping profiles "
                    "and journey annotations"
    )
    parser.add_argument(
        "--shopping_journey_file",
        type=str,
        default="/cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Data/LLMTrainingData/raw_data/shopping_journeys.json",
        help="Path to shopping_journeys.json from pre_s3_construct_shopping_journey "
    )
    parser.add_argument(
        "--shopping_profile_file",
        type=str,
        default="/cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Data/LLMTrainingData/raw_data/shopping_profiles.tsv",
        help="Path to shopping_profiles.tsv from pre_s3_construct_shopping_profile "
    )
    parser.add_argument(
        "--id2meta_file",
        type=str,
        default="/cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Data/LLMTrainingData/processed/id2meta.json",
        help="Path to id2meta JSON from s1_generate_tid "
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="/cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Data/LLMTrainingData/sft_data/",
        help="Output directory ",
    )
    parser.add_argument(
        "--max_recent_events",
        type=int,
        default=DEFAULT_MAX_RECENT_EVENTS,
        help=f"Number of most recent events to include in input "
             f"(default: {DEFAULT_MAX_RECENT_EVENTS})",
    )
    parser.add_argument(
        "--max_products_per_journey",
        type=int,
        default=DEFAULT_MAX_PRODUCTS,
        help=f"Maximum products per journey in output "
             f"(default: {DEFAULT_MAX_PRODUCTS})",
    )
    return parser.parse_args()


# =============================================================================
# Main
# =============================================================================

def main():
    args = parse_args()

    # =========================================================================
    # Step 1: Load input files
    # =========================================================================
    print("=" * 70)
    print("Step 1: Loading input files")
    print("=" * 70)

    print(f"  Loading shopping journeys: {args.shopping_journey_file}")
    with open(args.shopping_journey_file, "r", encoding="utf-8") as f:
        shopping_data = json.load(f)
    print(f"    Entries: {len(shopping_data):,}")

    print(f"  Loading shopping profiles: {args.shopping_profile_file}")
    profiles = load_shopping_profiles(args.shopping_profile_file)
    print(f"    Profiles: {len(profiles):,}")

    # Report join coverage
    journey_uids = set(shopping_data.keys())
    profile_uids = set(profiles.keys())
    overlap = journey_uids & profile_uids
    print(f"    Journey users with profile: {len(overlap):,} / {len(journey_uids):,} "
          f"({len(overlap) / max(len(journey_uids), 1) * 100:.1f}%)")

    print(f"  Loading id2meta: {args.id2meta_file}")
    with open(args.id2meta_file, "r", encoding="utf-8") as f:
        id2meta = json.load(f)
    print(f"    Items: {len(id2meta):,}")

    # Quick coverage check
    all_pids = set()
    for entry in shopping_data.values():
        for j in entry.get("journeys", []):
            all_pids.update(j.get("product_ids", []))
    has_tid = sum(1 for pid in all_pids if get_item_tid(pid, id2meta) is not None)
    print(f"    Distinct product IDs in journeys: {len(all_pids):,}")
    print(f"    With valid TID: {has_tid:,} ({has_tid / max(len(all_pids), 1) * 100:.1f}%)")

    # =========================================================================
    # Step 2: Build SFT data
    # =========================================================================
    print()
    print("=" * 70)
    print("Step 2: Building profile2journey SFT data")
    print(f"  max_recent_events = {args.max_recent_events}")
    print(f"  max_products_per_journey = {args.max_products_per_journey}")
    print("=" * 70)

    sft_data = create_profile2journey_sft_data(
        shopping_data,
        profiles,
        id2meta,
        max_recent_events=args.max_recent_events,
        max_products=args.max_products_per_journey,
    )

    # =========================================================================
    # Step 3: Save output
    # =========================================================================
    print()
    print("=" * 70)
    print("Step 3: Saving output")
    print("=" * 70)

    output_file = os.path.join(args.output_dir, "profile2journey_sft.json")
    save_sft_data(sft_data, output_file)

    # =========================================================================
    # Step 4: Show example cases
    # =========================================================================
    print(f"\n{'=' * 70}")
    print("Example cases (first 3):")
    print(f"{'=' * 70}")
    for idx, sample in enumerate(sft_data[:3]):
        meta = sample["metadata"]
        print(f"\n--- Example {idx + 1} ---")
        print(f"  User ID:        {meta['user_id']}")
        print(f"  Recent events:  {meta['num_recent_events']}")
        print(f"  Num journeys:   {meta['num_journeys']}")
        print(f"  Products/j:     {meta['num_products_per_journey']}")
        print(f"  Instruction:    {sample['instruction'][:100]}...")
        print(f"  Input (first 8 lines):")
        for line in sample["input"].split("\n")[:8]:
            print(f"    {line[:120]}")
        # Pretty-print the output JSON
        try:
            out_obj = json.loads(sample["output"])
            for ji, j in enumerate(out_obj["ContinuedJourneys"][:2]):
                print(f"  Journey {ji+1}: {j['Title']}")
                print(f"    Reason: {j['Reason']}")
                print(f"    Products: {len(j['ProductTIDs'])} TIDs")
                if j["ProductTIDs"]:
                    print(f"      [0]: {j['ProductTIDs'][0]}")
        except (json.JSONDecodeError, KeyError):
            print(f"  Output: {sample['output'][:200]}...")
    print(f"\n{'=' * 70}")

    print(f"\nDone! Generated {len(sft_data)} training samples")


if __name__ == "__main__":
    main()
